import React, { useState } from 'react';
import { 
  Sparkles, 
  Search, 
  ChevronRight, 
  Workflow
} from 'lucide-react';
import { useAura } from '../../context/AuraContext';

export const InsightsView: React.FC = () => {
  const { intelligenceFeed, setActiveNav, setIsWorkflowBuilderOpen, setSelectedInsight, monochromeMode } = useAura();
  const [selectedDept, setSelectedDept] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState('');

  const isLight = monochromeMode === 'light';

  const departments = ['All', 'Marketing', 'Sales', 'Finance', 'Operations', 'HR'];

  const filteredFeed = intelligenceFeed.filter((item) => {
    const matchesDept = selectedDept === 'All' || item.department === selectedDept;
    const matchesQuery = item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         item.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         item.agentName.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesDept && matchesQuery;
  });

  const handleInsightClick = (insightId: string) => {
    const item = intelligenceFeed.find((i) => i.id === insightId);
    if (item) {
      if (item.id === 'insight-mkt-1') {
        setActiveNav('marketing-agent');
      } else {
        setSelectedInsight(item);
      }
    }
  };

  return (
    <div className="space-y-6 pb-16 animate-in fade-in duration-200">
      {/* Header */}
      <div className={`flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b pb-4 ${
        isLight ? 'border-neutral-200' : 'border-neutral-800'
      }`}>
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-xs font-mono uppercase tracking-wider ${isLight ? 'text-neutral-500' : 'text-neutral-400'}`}>
              Cross-System Signal Engine
            </span>
            <span className={isLight ? 'text-neutral-300' : 'text-neutral-700'}>·</span>
            <span className={`text-xs font-mono ${isLight ? 'text-neutral-600' : 'text-neutral-400'}`}>
              47 Insights Discovered Today
            </span>
          </div>
          <h1 className={`text-2xl font-bold tracking-tight ${isLight ? 'text-black' : 'text-white'}`}>
            Organizational Insights Feed
          </h1>
          <p className={`text-xs mt-1 ${isLight ? 'text-neutral-600' : 'text-neutral-400'}`}>
            Real-time causal analysis generated by departmental agents detecting anomalies, bottlenecks, and growth opportunities.
          </p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className={`flex flex-col sm:flex-row items-center justify-between gap-3 p-3 rounded-xl border ${
        isLight ? 'bg-neutral-50 border-neutral-300' : 'bg-neutral-950 border-neutral-800'
      }`}>
        <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto scrollbar-none pb-1 sm:pb-0">
          {departments.map((dept) => (
            <button
              key={dept}
              onClick={() => setSelectedDept(dept)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium font-mono uppercase transition-all whitespace-nowrap border ${
                selectedDept === dept
                  ? isLight
                    ? 'bg-black text-white border-black font-semibold'
                    : 'bg-white text-black border-white font-semibold'
                  : isLight
                    ? 'text-neutral-600 hover:text-black hover:bg-neutral-200/60 border-transparent'
                    : 'text-neutral-400 hover:text-white hover:bg-neutral-900 border-transparent'
              }`}
            >
              {dept}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search className={`w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 ${
            isLight ? 'text-neutral-400' : 'text-neutral-500'
          }`} />
          <input
            type="text"
            placeholder="Search insights..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className={`w-full pl-8 pr-3 py-1.5 rounded-lg border text-xs focus:outline-none transition-colors ${
              isLight 
                ? 'bg-white border-neutral-300 text-black placeholder-neutral-400 focus:border-black' 
                : 'bg-black border-neutral-800 text-white placeholder-neutral-500 focus:border-white'
            }`}
          />
        </div>
      </div>

      {/* Insights List */}
      <div className="space-y-3">
        {filteredFeed.map((insight) => {
          const isHero = insight.isHero;
          return (
            <div
              key={insight.id}
              onClick={() => handleInsightClick(insight.id)}
              className={`p-5 rounded-xl cursor-pointer transition-all border group ${
                isHero
                  ? isLight
                    ? 'bg-neutral-100/70 border-black shadow-sm'
                    : 'bg-neutral-900/80 border-white shadow-sm'
                  : isLight
                    ? 'bg-white border-neutral-300 hover:border-black'
                    : 'bg-neutral-950 border-neutral-800 hover:border-neutral-600'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2.5">
                  <span className={`text-xs font-bold font-mono ${isLight ? 'text-black' : 'text-white'}`}>
                    {insight.agentName}
                  </span>
                  <span className={isLight ? 'text-neutral-300' : 'text-neutral-700'}>·</span>
                  <span className={`text-[11px] font-mono ${isLight ? 'text-neutral-500' : 'text-neutral-400'}`}>
                    {insight.timestamp}
                  </span>
                  {isHero && (
                    <span className={`text-[9px] font-mono px-2 py-0.5 rounded uppercase font-semibold border ${
                      isLight 
                        ? 'bg-black text-white border-black' 
                        : 'bg-white text-black border-white'
                    }`}>
                      Hero Anomaly
                    </span>
                  )}
                </div>

                <div className={`flex items-center gap-1.5 text-xs font-medium ${
                  isLight ? 'text-neutral-500 group-hover:text-black' : 'text-neutral-400 group-hover:text-white'
                }`}>
                  <span>Inspect Diagnosis</span>
                  <ChevronRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-0.5" />
                </div>
              </div>

              <h2 className={`text-sm font-bold transition-colors mb-2 ${
                isLight ? 'text-black group-hover:text-neutral-800' : 'text-white group-hover:text-neutral-200'
              }`}>
                &ldquo;{insight.title}&rdquo;
              </h2>
              <p className={`text-xs leading-relaxed mb-3 ${
                isLight ? 'text-neutral-700' : 'text-neutral-300'
              }`}>
                {insight.summary}
              </p>

              {/* Factors list if available */}
              {insight.whyDetails && (
                <div className={`mt-2 pt-3 border-t space-y-1.5 ${
                  isLight ? 'border-neutral-200' : 'border-neutral-800'
                }`}>
                  <div className={`text-[10px] font-mono uppercase tracking-wider ${
                    isLight ? 'text-neutral-500' : 'text-neutral-400'
                  }`}>
                    Key Contributing Signals:
                  </div>
                  {insight.whyDetails.factors.map((f, i) => (
                    <div key={i} className={`text-xs flex items-start gap-2 ${
                      isLight ? 'text-neutral-600' : 'text-neutral-400'
                    }`}>
                      <span className={`font-bold ${isLight ? 'text-black' : 'text-white'}`}>•</span>
                      <span>{f}</span>
                    </div>
                  ))}
                </div>
              )}

              {isHero && (
                <div className={`mt-4 pt-3 border-t flex flex-wrap items-center justify-between gap-2 ${
                  isLight ? 'border-neutral-200' : 'border-neutral-800'
                }`}>
                  <span className={`text-xs font-mono ${isLight ? 'text-neutral-600' : 'text-neutral-400'}`}>
                    Depresses weekly qualified lead volume into Sales SDR queue.
                  </span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setActiveNav('marketing-agent');
                      setIsWorkflowBuilderOpen(true);
                    }}
                    className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-sm ${
                      isLight
                        ? 'bg-black hover:bg-neutral-800 text-white'
                        : 'bg-white hover:bg-neutral-200 text-black'
                    }`}
                  >
                    <Workflow className="w-3.5 h-3.5" />
                    <span>Create Optimization Workflow</span>
                  </button>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
